### ISSUE TITLE
Crash when storage crate is moved by CarryOn

### ISSUE THREAD

**Issue by maksim789456** [copygirl/BetterStorage#326]
Hey
I found a bug. When a block gets from the Storage crate structure with the help of CarryOn, it is linked with a large structure.
![2018-09-30_14 31 15](https://user-images.githubusercontent.com/8225008/46256576-9b68cd80-c4bd-11e8-9ef7-e1ddb23c5ae1.png)
![2018-09-30_14 31 20](https://user-images.githubusercontent.com/8225008/46256577-9b68cd80-c4bd-11e8-8bc9-14f145ffba71.png)
![2018-09-30_14 31 23](https://user-images.githubusercontent.com/8225008/46256578-9b68cd80-c4bd-11e8-966d-6e93373ab170.png)

Crash when interacting with related unit
https://pastebin.com/5cNKW8QQ

**Comment by copygirl** [comment]
This is unfortunately because of the arguably weird implementation of crates which makes them awesome but unfortunately unable to deal with being moved around in any sensible way. I recommend blacklisting crates in CarryOn.

Also I noticed you're running on 1.12.2. I've only maintained BetterStorage until 1.7.10 so you may try reporting this issue to the author of the 1.12.2 version of the mod. Also please let me know who's been working on it, I didn't know one existed and I'm actually curious.

**Comment by maksim789456** [comment]
https://github.com/TehStoneMan/BetterStorageToo
It seems that the repository mod under 1.12
